export interface Challenge {
  /**
   * The unique identifier of the challenge
   * @todo Decide whether it is a slug or it is a uuid generated by Firebase
   */
  id: string;
  /**
   * The title of the challenge
   */
  name: string;
  /**
   * A short description of the challenge, in plain text
   */
  intro?: string;
  /**
   * A long explanation of the challenge, in html markup
   */
  description?: string
}